"""Added user table

Revision ID: 17d43b9c89b5
Revises:
Create Date: 2023-06-06 22:20:10.452288

"""

# revision identifiers, used by Alembic.
revision = "17d43b9c89b5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
